import type { NewDesignToken } from "./schema";

// Default design tokens applied to every new portfolio
export function getDefaultTokens(portfolioId: string): NewDesignToken[] {
  const now = new Date().toISOString();

  const tokens: Omit<NewDesignToken, "id">[] = [
    // ── Colors ──────────────────────────────
    {
      portfolioId,
      key: "--color-primary",
      value: "#6C63FF",
      darkValue: "#7C74FF",
      label: "Primary",
      category: "color",
      type: "color",
      defaultValue: "#6C63FF",
      sortOrder: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-primary-hover",
      value: "#5a52e0",
      darkValue: "#6a62f0",
      label: "Primary Hover",
      category: "color",
      type: "color",
      defaultValue: "#5a52e0",
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-accent",
      value: "#FF6584",
      darkValue: "#FF7594",
      label: "Accent",
      category: "color",
      type: "color",
      defaultValue: "#FF6584",
      sortOrder: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-background",
      value: "#ffffff",
      darkValue: "#0f0f0f",
      label: "Background",
      category: "color",
      type: "color",
      defaultValue: "#ffffff",
      sortOrder: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-surface",
      value: "#f8f8f8",
      darkValue: "#1a1a1a",
      label: "Surface",
      category: "color",
      type: "color",
      defaultValue: "#f8f8f8",
      sortOrder: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-text-primary",
      value: "#111111",
      darkValue: "#f0f0f0",
      label: "Text Primary",
      category: "color",
      type: "color",
      defaultValue: "#111111",
      sortOrder: 5,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-text-secondary",
      value: "#555555",
      darkValue: "#aaaaaa",
      label: "Text Secondary",
      category: "color",
      type: "color",
      defaultValue: "#555555",
      sortOrder: 6,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-border",
      value: "#e5e5e5",
      darkValue: "#2a2a2a",
      label: "Border",
      category: "color",
      type: "color",
      defaultValue: "#e5e5e5",
      sortOrder: 7,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--color-heading",
      value: "#111111",
      darkValue: "#ffffff",
      label: "Heading Color",
      category: "color",
      type: "color",
      defaultValue: "#111111",
      sortOrder: 8,
      createdAt: now,
      updatedAt: now,
    },

    // ── Typography ───────────────────────────
    {
      portfolioId,
      key: "--font-heading",
      value: "'Sora', sans-serif",
      darkValue: null,
      label: "Heading Font",
      category: "typography",
      type: "font-family",
      defaultValue: "'Sora', sans-serif",
      options: JSON.stringify([
        "Sora", "Inter", "Poppins", "Raleway", "Playfair Display",
        "DM Sans", "Space Grotesk", "Outfit", "Fraunces", "Cabinet Grotesk",
      ]),
      sortOrder: 20,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--font-body",
      value: "'DM Sans', sans-serif",
      darkValue: null,
      label: "Body Font",
      category: "typography",
      type: "font-family",
      defaultValue: "'DM Sans', sans-serif",
      options: JSON.stringify([
        "DM Sans", "Inter", "Lato", "Nunito", "Source Sans 3",
        "Mulish", "Work Sans", "Hind", "Noto Sans",
      ]),
      sortOrder: 21,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--font-size-base",
      value: "16px",
      darkValue: null,
      label: "Base Font Size",
      category: "typography",
      type: "px",
      defaultValue: "16px",
      options: JSON.stringify(["14px", "15px", "16px", "17px", "18px"]),
      sortOrder: 22,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--font-weight-heading",
      value: "700",
      darkValue: null,
      label: "Heading Weight",
      category: "typography",
      type: "select",
      defaultValue: "700",
      options: JSON.stringify(["400", "500", "600", "700", "800", "900"]),
      sortOrder: 23,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--line-height-body",
      value: "1.7",
      darkValue: null,
      label: "Body Line Height",
      category: "typography",
      type: "select",
      defaultValue: "1.7",
      options: JSON.stringify(["1.4", "1.5", "1.6", "1.7", "1.8", "2"]),
      sortOrder: 24,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--letter-spacing-heading",
      value: "-0.02em",
      darkValue: null,
      label: "Heading Letter Spacing",
      category: "typography",
      type: "select",
      defaultValue: "-0.02em",
      options: JSON.stringify(["-0.05em", "-0.03em", "-0.02em", "0", "0.02em", "0.05em"]),
      sortOrder: 25,
      createdAt: now,
      updatedAt: now,
    },

    // ── Spacing & Layout ─────────────────────
    {
      portfolioId,
      key: "--section-padding-y",
      value: "96px",
      darkValue: null,
      label: "Section Vertical Padding",
      category: "spacing",
      type: "px",
      defaultValue: "96px",
      options: JSON.stringify(["48px", "64px", "80px", "96px", "120px", "160px"]),
      sortOrder: 40,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--container-max-width",
      value: "1200px",
      darkValue: null,
      label: "Container Max Width",
      category: "spacing",
      type: "select",
      defaultValue: "1200px",
      options: JSON.stringify(["960px", "1100px", "1200px", "1400px", "1600px"]),
      sortOrder: 41,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--gap-cards",
      value: "24px",
      darkValue: null,
      label: "Cards Gap",
      category: "spacing",
      type: "px",
      defaultValue: "24px",
      options: JSON.stringify(["12px", "16px", "20px", "24px", "32px", "40px"]),
      sortOrder: 42,
      createdAt: now,
      updatedAt: now,
    },

    // ── Border Radius ─────────────────────────
    {
      portfolioId,
      key: "--radius-sm",
      value: "4px",
      darkValue: null,
      label: "Radius Small",
      category: "radius",
      type: "px",
      defaultValue: "4px",
      sortOrder: 50,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--radius-md",
      value: "8px",
      darkValue: null,
      label: "Radius Medium",
      category: "radius",
      type: "px",
      defaultValue: "8px",
      sortOrder: 51,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--radius-lg",
      value: "16px",
      darkValue: null,
      label: "Radius Large",
      category: "radius",
      type: "px",
      defaultValue: "16px",
      sortOrder: 52,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--radius-full",
      value: "9999px",
      darkValue: null,
      label: "Radius Full (Pill)",
      category: "radius",
      type: "px",
      defaultValue: "9999px",
      sortOrder: 53,
      createdAt: now,
      updatedAt: now,
    },

    // ── Effects ──────────────────────────────
    {
      portfolioId,
      key: "--shadow-card",
      value: "0 4px 24px rgba(0,0,0,0.06)",
      darkValue: "0 4px 24px rgba(0,0,0,0.3)",
      label: "Card Shadow",
      category: "effect",
      type: "select",
      defaultValue: "0 4px 24px rgba(0,0,0,0.06)",
      options: JSON.stringify([
        "none",
        "0 1px 4px rgba(0,0,0,0.06)",
        "0 4px 24px rgba(0,0,0,0.06)",
        "0 8px 40px rgba(0,0,0,0.1)",
        "0 20px 60px rgba(0,0,0,0.15)",
      ]),
      sortOrder: 60,
      createdAt: now,
      updatedAt: now,
    },
    {
      portfolioId,
      key: "--transition-speed",
      value: "0.2s",
      darkValue: null,
      label: "Transition Speed",
      category: "effect",
      type: "select",
      defaultValue: "0.2s",
      options: JSON.stringify(["0.1s", "0.15s", "0.2s", "0.3s", "0.5s"]),
      sortOrder: 61,
      createdAt: now,
      updatedAt: now,
    },
  ];

  return tokens.map((t) => ({
    ...t,
    id: crypto.randomUUID(),
    options: t.options ?? null,
  }));
}