import type { NewPlan } from "./schema";

// Default plans seed data
export const defaultPlans: NewPlan[] = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for getting started",
    priceMonthly: 0,
    priceYearly: 0,
    isActive: true,
    sortOrder: 0,
    maxPortfolios: 1,
    allowCustomDomain: false,
    allowCustomScripts: false,
    allowAdvancedSeo: false,
    allowAnalytics: false,
    allowPasswordProtect: false,
    allowRemoveBranding: false,
    maxMediaMb: 100,
    maxSections: 8,
    supportLevel: "community",
  },
  {
    id: "pro",
    name: "Pro",
    description: "For professionals who want full control",
    priceMonthly: 9,
    priceYearly: 79,
    isActive: true,
    sortOrder: 1,
    maxPortfolios: 1,
    allowCustomDomain: true,
    allowCustomScripts: true,
    allowAdvancedSeo: true,
    allowAnalytics: true,
    allowPasswordProtect: true,
    allowRemoveBranding: false,
    maxMediaMb: 1024,
    maxSections: 30,
    supportLevel: "email",
  },
  {
    id: "business",
    name: "Business",
    description: "For agencies and power users",
    priceMonthly: 29,
    priceYearly: 249,
    isActive: true,
    sortOrder: 2,
    maxPortfolios: 1,
    allowCustomDomain: true,
    allowCustomScripts: true,
    allowAdvancedSeo: true,
    allowAnalytics: true,
    allowPasswordProtect: true,
    allowRemoveBranding: true,
    maxMediaMb: 10240,
    maxSections: 999,
    supportLevel: "priority",
  },
];